---
title: "sample rmd"
author: ''
date: '2017-05-30'
slug: sample-rmd
categories: R
tags: blogdown
---

##Performing Univariate Analysis
```{r include=FALSE}
ipak <- function(pkg){
    new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
    if (length(new.pkg)) 
        install.packages(new.pkg, repos = "http://cran.us.r-project.org", dependencies = TRUE)
    sapply(pkg, require, character.only = TRUE)
}

# usage
packages <- c("car", "pastecs", "Hmisc")
ipak(packages)
```

```{r}
# install.packages("car")
library(car)
```

```{r}
data(Prestige, package = "car")
ls()
head(Prestige)
```
```{r}
str(Prestige)
```


```{r}
mean(Prestige$income)
mean(Prestige$income, na.rm = T)
median(Prestige$income, na.rm = T)
sd(Prestige$income, na.rm = T)
var(Prestige$income, na.rm = T)
quantile(Prestige$income, probs = c(0.01, 0.05, 0.1, 0.25, 0.5, 0.75, 0.90, 0.95))
```

```{r}
summary(Prestige)
```

```{r, eval=FALSE, include=TRUE}
#install.packages("pastecs")
```

```{r,eval=FALSE, include=TRUE}
??pastecs
```

```{r}
pastecs::stat.desc(Prestige)
```


```{r}
dim(Prestige)
```

```{r}
library(Hmisc)
```


```{r}
describe(Prestige)
```

```{r}
print(barplot(table(Prestige$type)))
```
```{r}
print("from local")
```

